import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { MapPin, Save, Store, MessageCircle } from "lucide-react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { defaultStoreSettings } from "@/lib/settings.functions";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/admin/_layout/settings")({ component: Settings });
function Settings() {
  const queryClient = useQueryClient();
  const query = useQuery({ queryKey: ["store-settings"], queryFn: async () => { const { data, error } = await supabase.from("store_settings").select("business_name,whatsapp_number,map_url").eq("id", 1).maybeSingle(); if (error) throw error; return data ?? defaultStoreSettings; } });
  const [name, setName] = useState(""); const [number, setNumber] = useState(""); const [mapUrl, setMapUrl] = useState(""); const [saving, setSaving] = useState(false);
  useEffect(() => { if (query.data) { setName(query.data.business_name); setNumber(query.data.whatsapp_number); setMapUrl(query.data.map_url); } }, [query.data]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); const normalized = number.replace(/[^0-9]/g, ""); if (!name.trim() || !normalized || !mapUrl.trim()) return toast.error("أدخل اسم المتجر ورقم واتساب ورابط الخريطة."); setSaving(true); const { error } = await supabase.from("store_settings").upsert({ id: 1, business_name: name.trim(), whatsapp_number: normalized, map_url: mapUrl.trim() }); setSaving(false); if (error) return toast.error(error.message); queryClient.invalidateQueries({ queryKey: ["store-settings"] }); toast.success("تم حفظ إعدادات المتجر"); };
  return <form onSubmit={save} className="mx-auto max-w-3xl space-y-6"><div><p className="text-sm font-bold text-primary">إدارة المتجر</p><h2 className="mt-1 text-2xl font-black">إعدادات الموقع</h2><p className="mt-1 text-sm text-muted-foreground">غيّر البيانات التي تظهر للعميل في الموقع وأزرار التواصل.</p></div><section className="rounded-2xl border border-border/80 bg-card p-5 shadow-card"><div className="mb-6 flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-primary/10 text-primary"><Store className="h-5 w-5"/></span><div><h3 className="font-black">هوية المتجر</h3><p className="mt-1 text-xs text-muted-foreground">يظهر الاسم في الشعار والعناوين.</p></div></div><label className="block text-sm font-black">اسم المتجر<input value={name} onChange={event => setName(event.target.value)} placeholder="مثال: أبو عمر" className="admin-input mt-2"/></label></section><section className="rounded-2xl border border-border/80 bg-card p-5 shadow-card"><div className="mb-6 flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-success/10 text-success"><MessageCircle className="h-5 w-5"/></span><div><h3 className="font-black">واتساب</h3><p className="mt-1 text-xs text-muted-foreground">يُستخدم في زر الطلب والتواصل.</p></div></div><label className="block text-sm font-black">رقم واتساب بصيغة دولية<input dir="ltr" inputMode="numeric" value={number} onChange={event => setNumber(event.target.value)} placeholder="201274498847" className="admin-input mt-2"/><span className="mt-2 block text-xs font-normal text-muted-foreground">مثال مصر: 201xxxxxxxxx، بدون علامة + أو مسافات.</span></label></section><section className="rounded-2xl border border-border/80 bg-card p-5 shadow-card"><div className="mb-6 flex gap-3"><span className="grid h-10 w-10 place-items-center rounded-xl bg-accent/30 text-accent-foreground"><MapPin className="h-5 w-5"/></span><div><h3 className="font-black">موقع المحل</h3><p className="mt-1 text-xs text-muted-foreground">يظهر رابط الخريطة في تذييل الموقع.</p></div></div><label className="block text-sm font-black">رابط Google Maps<input dir="ltr" type="url" value={mapUrl} onChange={event => setMapUrl(event.target.value)} placeholder="https://maps.app.goo.gl/..." className="admin-input mt-2"/></label>{mapUrl && <a href={mapUrl} target="_blank" rel="noopener noreferrer" className="mt-3 inline-flex text-sm font-bold text-primary hover:underline">فتح الموقع على الخريطة ←</a>}</section><Button type="submit" disabled={saving}><Save />{saving ? "جاري الحفظ..." : "حفظ الإعدادات"}</Button></form>;
}
