import { useEffect, useState } from "react";
import { Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, FolderTree, Save } from "lucide-react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
type Cat = { id: string; name: string; slug: string; parent_id: string | null; sort_order: number };
const slugify = (value: string) => value.trim().toLowerCase().replace(/[^\p{L}\p{N}]+/gu, "-").replace(/^-|-$/g, "") || `category-${Date.now()}`;

export function CategoryForm({ category }: { category?: Cat }) {
  const navigate = useNavigate(); const [name, setName] = useState(category?.name ?? ""); const [slug, setSlug] = useState(category?.slug ?? ""); const [parent, setParent] = useState(category?.parent_id ?? ""); const [order, setOrder] = useState(String(category?.sort_order ?? 0)); const [categories, setCategories] = useState<Cat[]>([]); const [saving, setSaving] = useState(false);
  useEffect(() => { supabase.from("categories").select("id,name,slug,parent_id,sort_order").order("name").then(({ data, error }) => { if (error) return toast.error(error.message); const all = data ?? []; const blocked = new Set<string>(category ? [category.id] : []); let changed = true; while (changed) { changed = false; for (const item of all) if (item.parent_id && blocked.has(item.parent_id) && !blocked.has(item.id)) { blocked.add(item.id); changed = true; } } setCategories(all.filter(item => !blocked.has(item.id))); }); }, [category?.id]);
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!name.trim()) return toast.error("اسم التصنيف مطلوب"); setSaving(true); try { const values = { name: name.trim(), slug: slug.trim() || slugify(name), parent_id: parent || null, sort_order: Number(order) || 0 }; const result = category ? await supabase.from("categories").update(values).eq("id", category.id) : await supabase.from("categories").insert(values); if (result.error) throw result.error; toast.success(category ? "تم تحديث التصنيف" : "تم إنشاء التصنيف"); navigate({ to: "/admin/categories" }); } catch (error) { toast.error(error instanceof Error ? error.message : "تعذر حفظ التصنيف"); } finally { setSaving(false); } };
  return <form onSubmit={save} className="max-w-2xl space-y-5"><div><Link to="/admin/categories" className="inline-flex items-center gap-1 text-sm font-bold text-muted-foreground hover:text-primary"><ArrowRight className="h-4 w-4"/>كل التصنيفات</Link><h2 className="mt-3 text-2xl font-black">{category ? "تعديل التصنيف" : "إضافة تصنيف"}</h2><p className="mt-1 text-sm text-muted-foreground">حدّد الاسم والموقع داخل شجرة التصنيفات.</p></div><section className="rounded-2xl border border-border/80 bg-card p-5 shadow-card"><div className="mb-5 flex items-center gap-2"><div className="grid h-9 w-9 place-items-center rounded-xl bg-primary/10 text-primary"><FolderTree className="h-4 w-4"/></div><div><h3 className="font-black">بيانات التصنيف</h3><p className="text-xs text-muted-foreground">تظهر للعملاء في صفحة المنتجات.</p></div></div><div className="grid gap-5 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">اسم التصنيف<input autoFocus required value={name} onChange={e => { setName(e.target.value); if (!category) setSlug(slugify(e.target.value)); }} placeholder="مثال: هوجان أو F50" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10"/></label><label className="text-sm font-bold">الرابط المختصر<input dir="ltr" value={slug} onChange={e => setSlug(e.target.value)} placeholder="hojan-f50" className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10"/></label><label className="text-sm font-bold">ترتيب العرض<input type="number" value={order} onChange={e => setOrder(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10"/></label><label className="text-sm font-bold sm:col-span-2">التصنيف الأب<select value={parent} onChange={e => setParent(e.target.value)} className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10"><option value="">تصنيف رئيسي</option>{categories.map(item => <option key={item.id} value={item.id}>{item.parent_id ? "└ " : ""}{item.name}</option>)}</select><span className="mt-2 block text-xs font-normal text-muted-foreground">اتركه كتصنيف رئيسي، أو اختر العلامة التجارية / التصنيف الأب.</span></label></div></section><div className="flex flex-wrap gap-3"><Button type="submit" disabled={saving}><Save />{saving ? "جاري الحفظ..." : "حفظ التصنيف"}</Button><Button type="button" variant="outline" asChild><Link to="/admin/categories">إلغاء</Link></Button></div></form>;
}
