import { createFileRoute, Link } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { Edit3, FolderTree, ImageOff, PackagePlus, Search, SlidersHorizontal, Trash2 } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { formatPrice } from "@/lib/whatsapp";
import { EmptyState } from "@/components/site/EmptyState";
import { Button } from "@/components/ui/button";
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from "@/components/ui/alert-dialog";
export const Route = createFileRoute("/admin/products/")({ component: Products });
type Product = { id: string; name: string; price: number; status: "AVAILABLE" | "SOLD_OUT"; created_at: string; product_images: { image_url: string; is_primary: boolean }[] | null; product_categories: { categories: { name: string } | null }[] | null };
function Products() { const [term, setTerm] = useState(""); const [status, setStatus] = useState("all"); const queryClient = useQueryClient(); const query = useQuery({ queryKey: ["admin-products"], queryFn: async () => { const { data, error } = await supabase.from("products").select("id,name,price,status,created_at,product_images(image_url,is_primary),product_categories(categories(name))").order("created_at", { ascending: false }); if (error) throw error; return data as Product[]; } }); const products = useMemo(() => (query.data ?? []).filter(product => (status === "all" || product.status === status) && product.name.toLocaleLowerCase().includes(term.toLocaleLowerCase())), [query.data, status, term]); const remove = async (product: Product) => { const { data: images } = await supabase.from("product_images").select("image_url").eq("product_id", product.id); const paths = (images ?? []).map(image => image.image_url).filter(path => !path.startsWith("/") && !path.startsWith("http")); if (paths.length) await supabase.storage.from("product-images").remove(paths); const { error } = await supabase.from("products").delete().eq("id", product.id); if (error) return toast.error(error.message); toast.success(`تم حذف «${product.name}»`); queryClient.invalidateQueries({ queryKey: ["admin-products"] }); };
return <div className="space-y-6"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-bold text-primary">كتالوج المتجر</p><h2 className="mt-1 text-2xl font-black tracking-tight">المنتجات</h2><p className="mt-1 text-sm text-muted-foreground">إدارة الأسعار والحالة والصور والتصنيفات.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" asChild><Link to="/admin/categories"><FolderTree />إدارة التصنيفات</Link></Button><Button asChild><Link to="/admin/products/new"><PackagePlus />إضافة منتج</Link></Button></div></div><section className="rounded-2xl border border-border/80 bg-card shadow-card"><div className="grid gap-3 border-b border-border/80 p-4 md:grid-cols-[1fr_180px]"><label className="relative"><Search className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-muted-foreground"/><input value={term} onChange={event => setTerm(event.target.value)} placeholder="ابحث باسم المنتج..." className="h-10 w-full rounded-xl border border-input bg-background pr-10 pl-3 text-sm outline-none transition focus:border-primary focus:ring-4 focus:ring-primary/10"/></label><label className="relative"><SlidersHorizontal className="pointer-events-none absolute right-3 top-3 h-4 w-4 text-muted-foreground"/><select value={status} onChange={event => setStatus(event.target.value)} className="h-10 w-full appearance-none rounded-xl border border-input bg-background pr-10 pl-3 text-sm font-bold outline-none"><option value="all">كل الحالات</option><option value="AVAILABLE">متوفر</option><option value="SOLD_OUT">نفد</option></select></label></div>{query.isLoading ? <div className="space-y-3 p-4"><div className="h-16 animate-pulse rounded-xl bg-muted"/><div className="h-16 animate-pulse rounded-xl bg-muted"/></div> : !products.length ? <div className="p-5"><EmptyState title={term || status !== "all" ? "لا توجد منتجات مطابقة" : "لا توجد منتجات بعد"} hint="غيّر البحث أو أضف أول منتج إلى الكتالوج."/></div> : <><div className="hidden overflow-x-auto md:block"><table className="w-full text-right text-sm"><thead className="bg-muted/60 text-[11px] font-black tracking-wide text-muted-foreground"><tr><th className="px-5 py-3">المنتج</th><th className="px-4 py-3">التصنيفات</th><th className="px-4 py-3">السعر</th><th className="px-4 py-3">الحالة</th><th className="px-5 py-3 text-left">إجراءات</th></tr></thead><tbody>{products.map(product => <ProductRow key={product.id} product={product} onDelete={remove}/>)}</tbody></table></div><div className="grid divide-y divide-border/70 md:hidden">{products.map(product => <ProductCard key={product.id} product={product} onDelete={remove}/>)}</div></>}</section></div>; }
function Status({ value }: { value: Product["status"] }) { return <span className={`inline-flex rounded-full px-2.5 py-1 text-xs font-black ${value === "AVAILABLE" ? "bg-success/10 text-success" : "bg-primary/10 text-primary"}`}>{value === "AVAILABLE" ? "متوفر" : "نفد"}</span>; }
function Thumb({ product }: { product: Product }) { const path = product.product_images?.find(item => item.is_primary)?.image_url ?? product.product_images?.[0]?.image_url; const [src, setSrc] = useState(""); useEffect(() => { if (!path) return setSrc(""); if (path.startsWith("/") || path.startsWith("http")) return setSrc(path); let active = true; supabase.storage.from("product-images").createSignedUrl(path, 60 * 60).then(({ data }) => { if (active) setSrc(data?.signedUrl ?? supabase.storage.from("product-images").getPublicUrl(path).data.publicUrl); }); return () => { active = false; }; }, [path]); return <div className="grid h-10 w-10 shrink-0 place-items-center overflow-hidden rounded-xl bg-muted">{src ? <img src={src} alt="" className="h-full w-full object-cover"/> : <ImageOff className="h-4 w-4 text-muted-foreground"/>}</div>; }
function Actions({ product, onDelete }: { product: Product; onDelete: (product: Product) => Promise<void> }) { return <div className="flex items-center gap-1"><Button variant="ghost" size="icon" asChild><Link to="/admin/products/$id" params={{ id: product.id }} aria-label={`تعديل ${product.name}`}><Edit3 /></Link></Button><AlertDialog><AlertDialogTrigger asChild><Button variant="ghost" size="icon" className="text-muted-foreground hover:bg-destructive/10 hover:text-destructive" aria-label={`حذف ${product.name}`}><Trash2 /></Button></AlertDialogTrigger><AlertDialogContent dir="rtl"><AlertDialogHeader><AlertDialogTitle>حذف المنتج «{product.name}»؟</AlertDialogTitle><AlertDialogDescription>سيُحذف المنتج وصوره وروابط تصنيفاته نهائيًا. لا يمكن التراجع عن هذا الإجراء.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>إلغاء</AlertDialogCancel><AlertDialogAction onClick={() => onDelete(product)} className="bg-destructive text-destructive-foreground hover:bg-destructive/90">حذف المنتج</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>; }
function ProductRow({ product, onDelete }: { product: Product; onDelete: (product: Product) => Promise<void> }) { return <tr className="border-t border-border/70 transition hover:bg-muted/35"><td className="px-5 py-3"><div className="flex items-center gap-3"><Thumb product={product}/><div><p className="font-black">{product.name}</p><p className="mt-0.5 text-xs text-muted-foreground">{new Date(product.created_at).toLocaleDateString("ar-EG")}</p></div></div></td><td className="max-w-56 px-4 py-3 text-xs text-muted-foreground">{product.product_categories?.map(link => link.categories?.name).filter(Boolean).join("، ") || "—"}</td><td className="px-4 py-3 font-bold">{formatPrice(Number(product.price))}</td><td className="px-4 py-3"><Status value={product.status}/></td><td className="px-5 py-3"><Actions product={product} onDelete={onDelete}/></td></tr>; }
function ProductCard({ product, onDelete }: { product: Product; onDelete: (product: Product) => Promise<void> }) { return <article className="flex gap-3 p-4"><Thumb product={product}/><div className="min-w-0 flex-1"><div className="flex justify-between gap-2"><p className="truncate font-black">{product.name}</p><Status value={product.status}/></div><p className="mt-1 text-sm font-bold">{formatPrice(Number(product.price))}</p><p className="mt-1 truncate text-xs text-muted-foreground">{product.product_categories?.map(link => link.categories?.name).filter(Boolean).join("، ") || "بدون تصنيف"}</p><div className="mt-2"><Actions product={product} onDelete={onDelete}/></div></div></article>; }
